# Generated by Django 5.0.4 on 2026-04-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, verbose_name='Номер карты')),
                ('card_holder', models.CharField(max_length=255, verbose_name='Владелец карты')),
                ('card_bank', models.CharField(default='Uzum Bank', max_length=100, verbose_name='Банк')),
                ('amount_uzs', models.PositiveIntegerField(default=200000, verbose_name='Сумма для участников из Узбекистана (сум)')),
                ('amount_usd', models.PositiveIntegerField(default=20, verbose_name='Сумма для зарубежных участников (USD)')),
                ('contact_phone', models.CharField(default='+998 90 985 80 44', max_length=50, verbose_name='Телефон для связи')),
                ('contact_email', models.EmailField(default='conference@wicar.uz', max_length=254, verbose_name='Email для связи')),
                ('telegram_contact', models.CharField(default='+998 90 985 80 44', max_length=100, verbose_name='Telegram контакт')),
                ('description_uz', models.TextField(blank=True, default='Взнос за участие в конференции и публикацию одной статьи составляет 200 тысяч сумов. Взнос для участников из зарубежных стран составляет 20 долларов США. Организационный взнос оплачивается после одобрения участия организационным комитетом. Организационный взнос не взимается с иностранных участников, участвующих в конференции в онлайн-формате.', verbose_name='Описание на узбекском')),
                ('description_ru', models.TextField(blank=True, default='Взнос за участие в конференции и публикацию одной статьи составляет 200 тысяч сумов. Взнос для участников из зарубежных стран составляет 20 долларов США. Организационный взнос оплачивается после одобрения участия организационным комитетом. Организационный взнос не взимается с иностранных участников, участвующих в конференции в онлайн-формате.', verbose_name='Описание на русском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информация об оплате',
                'verbose_name_plural': 'Информация об оплате',
                'db_table': 'payment_info',
            },
        ),
    ]
