# Generated by Django 5.0.4 on 2026-04-11 14:02

import apps.files.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article', 'Статья'), ('plagiarism', 'Отчет о плагиате'), ('payment', 'Квитанция об оплате'), ('info_letter', 'Информационное письмо'), ('collection', 'Сборник'), ('program', 'Программа')], max_length=20, verbose_name='Тип файла')),
                ('file', models.FileField(upload_to=apps.files.models.file_upload_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='applications.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
