# Generated by Django 5.0.4 on 2026-04-11 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Учреждение/Организация')),
                ('direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление')),
                ('participation_format', models.CharField(blank=True, max_length=20, null=True, verbose_name='Формат участия')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('talk_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип доклада')),
                ('has_article', models.BooleanField(default=False, verbose_name='Статья загружена')),
                ('article_file', models.FileField(blank=True, null=True, upload_to='participants/articles/', verbose_name='Файл статьи')),
                ('has_plagiarism', models.BooleanField(default=False, verbose_name='Антиплагиат загружен')),
                ('plagiarism_file', models.FileField(blank=True, null=True, upload_to='participants/plagiarism/', verbose_name='Файл антиплагиата')),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='Оплата подтверждена')),
                ('payment_file', models.FileField(blank=True, null=True, upload_to='participants/payments/', verbose_name='Файл подтверждения оплаты')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_profile', to='applications.application', verbose_name='Заявка')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'db_table': 'participants',
                'ordering': ['-created_at'],
            },
        ),
    ]
