# Generated by Django 5.0.4 on 2026-04-12 04:30

import apps.conference_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('info_letter_1', '1-е информационное письмо'), ('info_letter_2', '2-е информационное письмо'), ('collection', 'Сборник тезисов'), ('program', 'Программа конференции')], max_length=20, unique=True, verbose_name='Тип файла')),
                ('file', models.FileField(upload_to=apps.conference_files.models.conference_file_path, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Файл конференции',
                'verbose_name_plural': 'Файлы конференции',
                'db_table': 'conference_files',
            },
        ),
    ]
