# Generated by Django 5.0.4 on 2026-04-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencefile',
            name='gallery_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на галерею (Google Drive)'),
        ),
    ]
