# Generated by Django 5.0.4 on 2026-04-14 11:35

import apps.conference_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_files', '0002_conferencefile_gallery_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.conference_files.models.conference_file_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='conferencefile',
            name='file_type',
            field=models.CharField(choices=[('info_letter_1', '1-е информационное письмо'), ('info_letter_2', '2-е информационное письмо'), ('collection', 'Сборник тезисов'), ('program', 'Программа конференции'), ('gallery', 'Галерея')], max_length=20, unique=True, verbose_name='Тип файла'),
        ),
    ]
