# Generated by Django 5.0.4 on 2026-04-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление')),
                ('participation_format', models.CharField(max_length=20, verbose_name='Формат участия')),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('talk_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип доклада')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
