# Generated by Django 5.0.4 on 2026-04-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_foreign',
            field=models.BooleanField(default=False, verbose_name='Иностранный участник'),
        ),
    ]
