import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ru' | 'en' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    'nav.home': 'Главная',
    'nav.about': 'О конференции',
    'nav.directions': 'Направления',
    'nav.dates': 'Даты',
    'nav.apply': 'Подать заявку',
    'nav.login': 'Войти',
    'nav.dashboard': 'Личный кабинет',
    'hero.title': 'Международная научно-практическая конференция WICAR-2026',
    'hero.subtitle': 'Инновации в управлении водными ресурсами для устойчивого развития',
    'hero.date': '19 мая 2026 г.',
    'hero.location': 'Ташкент, УМЭД',
    'hero.register': 'Регистрация участников',
    'hero.countdown.title': 'До окончания приема заявок осталось:',
    'hero.download.info1': '1-е Инфо письмо',
    'hero.download.info2': '2-е Инфо письмо',
    'hero.download.collection': 'Сборник тезисов',
    'hero.download.program': 'Программа конференции',
    'organizer.title': 'Организатор',
    'organizer.name': 'Университет мировой экономики и дипломатии (УМЭД)',
    'organizer.desc': 'Ведущее высшее учебное заведение Узбекистана, специализирующееся на подготовке специалистов в области международных отношений, экономики и права.',
    'committee.title': 'Комитеты конференции',
    'committee.org': 'Организационный комитет',
    'committee.prog': 'Программный комитет',
    'committee.chairman': 'Председатель',
    'committee.vice': 'Заместители председателя',
    'committee.members': 'Члены комитета',
    'about.title': 'О конференции',
    'about.goal.title': 'Цель конференции',
    'about.goal.desc': 'Комплексное изучение проблем эффективного управления водными ресурсами в аридных зонах в условиях изменения климата, разработка инновационных подходов и методов математического/компьютерного моделирования, обмен научными результатами и практическим опытом, расширение международного сотрудничества.',
    'about.format': 'Формат: гибридный (очно + онлайн)',
    'about.languages': 'Рабочие языки: узбекский, русский, английский',
    'directions.title': 'Тематические направления',
    'directions.1.title': 'Водная дипломатия и интегрированные подходы в международных отношениях',
    'directions.1.item1': 'Системный анализ в международных отношениях и мировой политике в сфере водной дипломатии',
    'directions.1.item2': 'Экономические, экологические и энергетические аспекты устойчивого развития',
    'directions.1.item3': 'Системные подходы к достижению ЦУР (SDGs)',
    'directions.2.title': 'Математическое и компьютерное моделирование оптимального управления водными ресурсами в условиях изменения климата',
    'directions.2.item1': 'Оптимальное управление водными ресурсами',
    'directions.2.item2': 'Моделирование динамики водных ресурсов и климатической изменчивости',
    'directions.2.item3': 'Методы прикладной и вычислительной математики в моделировании ирригационных систем',
    'directions.3.title': 'Экологические и гидрогеологические процессы в регионе Аральского моря',
    'directions.3.item1': 'Системный анализ гидрогеологических процессов региона Арала',
    'directions.3.item2': 'Использование ИИ, машинного обучения и Big Data для решения экологических задач',
    'directions.3.item3': 'Имитационное и стохастическое моделирование экологических и гидрогеологических процессов',
    'dates.title': 'Важные даты',
    'dates.item1.title': 'Прием заявок и тезисов',
    'dates.item1.date': 'до 10 мая 2026 г.',
    'dates.item2.title': 'Подтверждение участия',
    'dates.item2.date': 'до 12 мая 2026 г.',
    'dates.item3.title': 'Программа конференции',
    'dates.item3.date': '12 мая 2026 г.',
    'dates.item4.title': 'День конференции',
    'dates.item4.date': '19 мая 2026 г.',
    'fees.title': 'Организационный взнос',
    'fees.local': 'Участники из Узбекистана: 200 000 UZS',
    'fees.foreign.offline': 'Иностранные участники (очно): 20 USD',
    'fees.foreign.online': 'Иностранные участники (онлайн): Бесплатно',
    'fees.note': '* Оплата производится только после одобрения заявки оргкомитетом.',
    'publication.title': 'Публикация и требования',
    'publication.general': 'Материалы публикуются в сборнике с присвоением UDC, BBK, ISBN и DOI. Каждый участник получает сертификат.',
    'publication.req.title': 'Требования к оформлению',
    'publication.req.volume': 'Объем: 6–8 стр. (А4)',
    'publication.req.format': 'Формат: DOC/DOCX, шрифт Times New Roman 12pt',
    'publication.req.spacing': 'Межстрочный интервал: 1.5, отступ: 1.25 см, поля: 20 мм',
    'publication.req.originality': 'Оригинальность: не менее 70% (проверка автором)',
    'publication.req.files': 'Для подачи отправить на ttmm.conf@uwed.uz ТРИ файла: Статья, Антиплагиат, Информация.',
    'contact.title': 'Контакты',
    'contact.address': '100007, г. Ташкент, пр. Мустакиллик, 54',
    'contact.phone': '+998 90 985-80-44',
    'contact.email': 'ttmm.conf@uwed.uz',
    'contact.form.title': 'Связаться с нами',
    'contact.name': 'Ваше имя',
    'contact.message': 'Ваше сообщение',
    'contact.send': 'Отправить сообщение',
    'contact.success': 'Сообщение успешно отправлено!',
    'footer.rights': 'Все права защищены',
    // Auth
    'auth.login': 'Войти',
    'auth.register': 'Зарегистрироваться',
    'auth.login_success': 'Добро пожаловать!',
    'auth.login_error': 'Ошибка входа',
    'auth.register_success': 'Регистрация успешна! Теперь вы можете войти.',
    'auth.register_error': 'Ошибка регистрации',
    'auth.forgot': 'Забыли?',
    'auth.email_label': 'Email адрес',
    'auth.password_label': 'Пароль',
    'auth.email_placeholder': 'name@university.edu',
    'auth.full_name_label': 'Полное имя',
    'auth.phone_label': 'Номер телефона',
    'auth.full_name_placeholder': 'Иванов Иван Иванович',
    'auth.phone_placeholder': '+998 (__) ___-__-__',
    'auth.not_registered': 'Впервые на конференции?',
    'auth.already_registered': 'Уже зарегистрированы?',
    'auth.register_link': 'Регистрация',
    'auth.login_link': 'Войти',
    'auth.creating_account': 'Создание аккаунта...',
    'auth.processing': 'Обработка...',
    // Login page
    'login.title': 'Доступ к научному сообществу',
    'login.subtitle': 'Войдите в личный кабинет для управления вашими публикациями и участия в сессиях конференции.',
    'login.secure_access': 'Secure Access',
    'login.location': 'Tashkent, Uzbekistan',
    // Register page
    'register.title': 'Присоединяйтесь к научному диалогу',
    'register.publications': 'Публикации',
    'register.publications_desc': 'Возможность публикации в сборнике РИНЦ/Scopus',
    'register.networking': 'Нетворкинг',
    'register.networking_desc': 'Обмен опытом с ведущими экспертами отрасли',
    'register.certification': 'Сертификация',
    'register.certification_desc': 'Официальный сертификат участника конференции',
    'register.deadline': 'Registration closes: May 15, 2026',
    // Dashboard
    'dashboard.title': 'Личный кабинет',
    'dashboard.subtitle': 'Управление вашим участием в конференции WICAR-2026',
    'dashboard.overview': 'Обзор',
    'dashboard.settings': 'Настройки',
    'dashboard.participant': 'Участник',
    'dashboard.application_status': 'Статус заявки',
    'dashboard.no_application': 'Не создана',
    'dashboard.step_1': 'ШАГ 1',
    'dashboard.step_2': 'ШАГ 2',
    'dashboard.step_3': 'ШАГ 3',
    'dashboard.application_params': 'Параметры участия',
    'dashboard.file_uploads': 'Загрузка документов',
    'dashboard.save_changes': 'Сохранить изменения',
    'dashboard.create_application': 'Создать заявку',
    'dashboard.account_settings': 'Настройки аккаунта',
    'dashboard.account_settings_subtitle': 'Управление данными профиля и безопасностью',
    'dashboard.profile': 'ПРОФИЛЬ',
    'dashboard.personal_data': 'Личные данные',
    'dashboard.security': 'БЕЗОПАСНОСТЬ',
    'dashboard.change_password': 'Смена пароля',
    'dashboard.save_settings': 'Сохранить изменения',
    'dashboard.saving': 'Сохранение...',
    'dashboard.name_label': 'Имя',
    'dashboard.name_placeholder': 'Иванов Иван Иванович',
    'dashboard.email_label': 'Email',
    'dashboard.email_note': 'Email нельзя изменить',
    'dashboard.phone_label': 'Телефон',
    'dashboard.phone_placeholder': '+998 (__) ___-__-__',
    'dashboard.current_password_label': 'Текущий пароль',
    'dashboard.current_password_placeholder': 'Введите текущий пароль',
    'dashboard.new_password_label': 'Новый пароль',
    'dashboard.new_password_placeholder': 'Минимум 6 символов',
    'dashboard.confirm_password_label': 'Подтвердите пароль',
    'dashboard.confirm_password_placeholder': 'Повторите пароль',
    'dashboard.direction_label': 'Направление',
    'dashboard.direction_placeholder': 'Выберите направление',
    'dashboard.format_label': 'Формат участия',
    'dashboard.format_placeholder': 'Выберите формат',
    'dashboard.affiliation_label': 'Affiliation (Организация / ВУЗ)',
    'dashboard.affiliation_placeholder': 'Название организации',
    'dashboard.position_label': 'Position (Должность)',
    'dashboard.position_placeholder': 'Выберите должность',
    'dashboard.talk_type_label': 'Select Talk Type',
    'dashboard.talk_type_placeholder': 'Выберите тип доклада',
    'dashboard.direction_1': 'Водная дипломатия',
    'dashboard.direction_2': 'Математическое моделирование',
    'dashboard.direction_3': 'Экология Аральского региона',
    'dashboard.format_offline': 'Оффлайн (в Ташкенте)',
    'dashboard.format_online': 'Онлайн',
    'dashboard.is_foreign_label': 'Иностранный участник',
    'dashboard.is_foreign_desc': 'Отметьте если вы участник из зарубежной страны',
    'dashboard.position_professor': 'Professor',
    'dashboard.position_associate': 'Associate Professor',
    'dashboard.position_assistant': 'Assistant Professor',
    'dashboard.position_phd': 'PhD Student',
    'dashboard.position_researcher': 'Researcher',
    'dashboard.position_lecturer': 'Lecturer',
    'dashboard.position_undergrad': 'Undergraduate Student',
    'dashboard.position_other': 'Other',
    'dashboard.talk_plenary': 'Plenary (Пленарный доклад)',
    'dashboard.talk_section': 'Sectional (Секционный доклад)',
    'dashboard.talk_panel': 'Panel (Панельная дискуссия)',
    'dashboard.file_article': 'Научная статья',
    'dashboard.file_plagiarism': 'Антиплагиат',
    'dashboard.file_payment': 'Чек об оплате',
    'dashboard.file_desc_pdf': 'PDF, DOC, DOCX (до 10MB)',
    'dashboard.file_desc_img': 'JPG, PNG, GIF (до 5MB)',
    'dashboard.file_uploaded': 'Загружено',
    'dashboard.file_replace': 'Заменить',
    'dashboard.file_select': 'Выберите файл',
    'dashboard.file_uploading': 'Загрузка...',
    'dashboard.instructions': 'Инструкции',
    'dashboard.instr_1': 'Зарегистрируйтесь на конференции',
    'dashboard.instr_2': 'Создайте заявку, выбрав направление и формат',
    'dashboard.instr_3': 'Загрузите научную статью',
    'dashboard.instr_4': 'Загрузите отчёт об антиплагиате',
    'dashboard.instr_5': 'Оплатите оргвзнос и прикрепите чек',
    'dashboard.instr_6': 'Ожидайте подтверждения',
    'dashboard.status_approved': 'Одобрено',
    'dashboard.status_rejected': 'Отклонено',
    'dashboard.status_pending': 'На рассмотрении',
    'dashboard.loading': 'Загрузка...',
    'dashboard.fill_all_fields': 'Заполните все поля',
    'dashboard.save_success': 'Заявка сохранена',
    'dashboard.file_upload_success': 'Файл успешно загружен',
    'dashboard.file_uploading_toast': 'Загрузка файла...',
    'dashboard.delete_confirm': 'Удалить этот файл?',
    'dashboard.file_deleted': 'Файл удалён',
    'dashboard.fill_all_password_fields': 'Заполните все поля пароля',
    'dashboard.passwords_not_match': 'Пароли не совпадают',
    'dashboard.settings_saved': 'Настройки сохранены',
    'dashboard.error_prefix': 'Ошибка: ',
    'dashboard.file_upload_error_prefix': 'Ошибка загрузки: ',
    'dashboard.file_delete_error_prefix': 'Ошибка удаления: ',
    // Navbar
    'navbar.cabinet': 'Кабинет',
    'navbar.logout': 'Выйти',
    'navbar.lang_uz': "O'zbekcha",
    'navbar.lang_ru': 'Русский',
    'navbar.lang_en': 'English',
    // Home - Contact
    'contact.email_label': 'Email',
    'contact.phone_label': 'Телефон / Telegram',
    'contact.location_label': 'Локация',
    // Home - Footer
    'footer.navigation': 'Навигация',
    'footer.organizer': 'Организатор',
    'footer.developer_label': 'Разработчик',
    // Home - Countdown
    'countdown.days': 'дней',
    'countdown.hours': 'часов',
    'countdown.mins': 'мин',
    'countdown.secs': 'сек',
    // Home - Publication accordion
    'publication.req.files_title': 'Список файлов для отправки',
    'publication.req.file_paper': 'Статья',
    'publication.req.file_plagiarism': 'Антиплагиат',
    'publication.req.file_info': 'Информация',
    // Home - Committee members (org committee)
    'committee.org.chairman.name': 'Sodyq Safoev',
    'committee.org.chairman.role': 'First Deputy Chairman of the Senate, Rector of UWED',
    'committee.org.vice.1.name': 'Gulnoza Ismailova',
    'committee.org.vice.1.role': 'Vice-Rector for Science and Innovation, UWED',
    'committee.org.vice.2.name': 'Akram Umarov',
    'committee.org.vice.2.role': 'Deputy Director of the IAIS',
    'committee.org.vice.3.name': 'Durbek Amanov',
    'committee.org.vice.3.role': 'Director of the IAIS',
    'committee.org.vice.4.name': 'Olimjon Tuychiev',
    'committee.org.vice.4.role': 'Director of the Agency for Innovative Development',
    'committee.org.members.1.name': 'Mansur Gulyamov',
    'committee.org.members.1.role': 'IAIS Senior Fellow',
    'committee.org.members.2.name': 'Rustam Kayumov',
    'committee.org.members.2.role': 'Head of Department, UWED',
    'committee.org.members.3.name': 'Nodira Gafurova',
    'committee.org.members.3.role': 'Associate Professor, UWED',
    'committee.org.members.4.name': 'Azizbek Khonkhodjaev',
    'committee.org.members.4.role': 'Senior Lecturer, UWED',
    'committee.org.members.5.name': 'Dilnoza Sultanova',
    'committee.org.members.5.role': 'Researcher, IAIS',
    'committee.org.members.6.name': 'Jamshid Abdullaev',
    'committee.org.members.6.role': 'Expert, UWED',
    // Home - Committee members (program committee)
    'committee.prog.chairman.name': 'Sherzod Abdullaev',
    'committee.prog.chairman.role': 'Professor, Head of Department of International Relations',
    'committee.prog.vice.1.name': 'Alisher Fayzullaev',
    'committee.prog.vice.1.role': 'Professor, IAIS Senior Fellow',
    'committee.prog.vice.2.name': 'Etibor Sultanova',
    'committee.prog.vice.2.role': 'Head of Department of Social and Political Sciences',
    'committee.prog.vice.3.name': 'Ulugbek Khasanov',
    'committee.prog.vice.3.role': 'Professor, IAIS Fellow',
    'committee.prog.vice.4.name': 'Farkhod Tolipov',
    'committee.prog.vice.4.role': 'Director of Knowledge Caravan',
    'committee.prog.members.1.name': 'Bakhtiyor Ergashev',
    'committee.prog.members.1.role': "Director of Ma'no Center",
    'committee.prog.members.2.name': 'Anvar Nazirov',
    'committee.prog.members.2.role': 'Independent Expert',
    'committee.prog.members.3.name': 'Kamola Alieva',
    'committee.prog.members.3.role': 'Associate Professor, UWED',
    'committee.prog.members.4.name': 'Sardorbek Usmanov',
    'committee.prog.members.4.role': 'Senior Researcher, IAIS',
    'committee.prog.members.5.name': 'Nilufar Rakhimova',
    'committee.prog.members.5.role': 'Lecturer, UWED',
    'committee.prog.members.6.name': 'Sherzodbek Khaydarov',
    'committee.prog.members.6.role': 'Expert, IAIS',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.directions': 'Directions',
    'nav.dates': 'Dates',
    'nav.apply': 'Apply Now',
    'nav.login': 'Login',
    'nav.dashboard': 'Dashboard',
    'hero.title': 'International Scientific and Practical Conference WICAR-2026',
    'hero.subtitle': 'Innovations in Water Resources Management for Sustainable Development',
    'hero.date': 'May 19, 2026',
    'hero.location': 'Tashkent, UWED',
    'hero.register': 'Register Now',
    'hero.countdown.title': 'Time remaining until deadline:',
    'hero.download.info1': '1st Info Letter',
    'hero.download.info2': '2nd Info Letter',
    'hero.download.collection': 'Proceedings',
    'hero.download.program': 'Conference Program',
    'organizer.title': 'Organizer',
    'organizer.name': 'University of World Economy and Diplomacy (UWED)',
    'organizer.desc': 'The leading higher education institution in Uzbekistan specializing in training specialists in international relations, economics, and law.',
    'committee.title': 'Conference Committees',
    'committee.org': 'Organizing Committee',
    'committee.prog': 'Program Committee',
    'committee.chairman': 'Chairman',
    'committee.vice': 'Vice-Chairmen',
    'committee.members': 'Committee Members',
    'about.title': 'About Conference',
    'about.goal.title': 'Conference Goal',
    'about.goal.desc': 'Comprehensive study of the problems of effective water resources management in arid zones under climate change conditions, development of innovative approaches and methods of mathematical/computer modeling, exchange of scientific results and practical experience, expansion of international cooperation.',
    'about.format': 'Format: Hybrid (In-person + Online)',
    'about.languages': 'Working languages: Uzbek, Russian, English',
    'directions.title': 'Thematic Tracks',
    'directions.1.title': 'Water Diplomacy and Integrated Approaches in International Relations',
    'directions.1.item1': 'System analysis in international relations and world politics in the field of water diplomacy',
    'directions.1.item2': 'Economic, environmental and energy aspects of sustainable development',
    'directions.1.item3': 'Systemic approaches to achieving SDGs',
    'directions.2.title': 'Mathematical and Computer Modeling of Optimal Water Resources Management under Climate Change',
    'directions.2.item1': 'Optimal water resources management',
    'directions.2.item2': 'Modeling of water resources dynamics and climate variability',
    'directions.2.item3': 'Methods of applied and computational mathematics in modeling irrigation systems',
    'directions.3.title': 'Ecological and Hydrogeological Processes in the Aral Sea Region',
    'directions.3.item1': 'System analysis of hydrogeological processes in the Aral region',
    'directions.3.item2': 'Use of AI, machine learning and Big Data to solve environmental problems',
    'directions.3.item3': 'Simulation and stochastic modeling of environmental and hydrogeological processes',
    'dates.title': 'Important Dates',
    'dates.item1.title': 'Submission of abstracts',
    'dates.item1.date': 'until May 10, 2026',
    'dates.item2.title': 'Confirmation of participation',
    'dates.item2.date': 'until May 12, 2026',
    'dates.item3.title': 'Conference program',
    'dates.item3.date': 'May 12, 2026',
    'dates.item4.title': 'Conference day',
    'dates.item4.date': 'May 19, 2026',
    'fees.title': 'Registration Fee',
    'fees.local': 'Participants from Uzbekistan: 200,000 UZS',
    'fees.foreign.offline': 'International participants (in-person): 20 USD',
    'fees.foreign.online': 'International participants (online): Free',
    'fees.note': '* Payment is made only after approval of the application by the organizing committee.',
    'publication.title': 'Publication and Requirements',
    'publication.general': 'Materials are published in a collection with UDC, BBK, ISBN and DOI. Each participant receives a certificate.',
    'publication.req.title': 'Formatting Requirements',
    'publication.req.volume': 'Volume: 6–8 pages (A4)',
    'publication.req.format': 'Format: DOC/DOCX, Times New Roman 12pt',
    'publication.req.spacing': 'Line spacing: 1.5, indent: 1.25 cm, margins: 20 mm',
    'publication.req.originality': 'Originality: at least 70% (checked by author)',
    'publication.req.files': 'To submit, send THREE files to ttmm.conf@uwed.uz: Paper, Plagiarism Report, Information.',
    'contact.title': 'Contacts',
    'contact.address': '54 Mustaqillik Ave, Tashkent, 100007',
    'contact.phone': '+998 90 985-80-44',
    'contact.email': 'ttmm.conf@uwed.uz',
    'contact.form.title': 'Contact Us',
    'contact.name': 'Your Name',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.success': 'Message sent successfully!',
    'footer.rights': 'All rights reserved',
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.login_success': 'Welcome!',
    'auth.login_error': 'Login error',
    'auth.register_success': 'Registration successful! You can now login.',
    'auth.register_error': 'Registration error',
    'auth.forgot': 'Forgot?',
    'auth.email_label': 'Email Address',
    'auth.password_label': 'Password',
    'auth.email_placeholder': 'name@university.edu',
    'auth.full_name_label': 'Full Name',
    'auth.phone_label': 'Phone Number',
    'auth.full_name_placeholder': 'John Doe',
    'auth.phone_placeholder': '+998 (__) ___-__-__',
    'auth.not_registered': 'First time at the conference?',
    'auth.already_registered': 'Already registered?',
    'auth.register_link': 'Register',
    'auth.login_link': 'Login',
    'auth.creating_account': 'Creating account...',
    'auth.processing': 'Processing...',
    // Login page
    'login.title': 'Access to the scientific community',
    'login.subtitle': 'Log in to your dashboard to manage your publications and participate in conference sessions.',
    'login.secure_access': 'Secure Access',
    'login.location': 'Tashkent, Uzbekistan',
    // Register page
    'register.title': 'Join the scientific dialogue',
    'register.publications': 'Publications',
    'register.publications_desc': 'Opportunity to publish in RINTC/Scopus proceedings',
    'register.networking': 'Networking',
    'register.networking_desc': 'Exchange experience with leading industry experts',
    'register.certification': 'Certification',
    'register.certification_desc': 'Official conference participant certificate',
    'register.deadline': 'Registration closes: May 15, 2026',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Manage your participation in WICAR-2026 conference',
    'dashboard.overview': 'Overview',
    'dashboard.settings': 'Settings',
    'dashboard.participant': 'Participant',
    'dashboard.application_status': 'Application Status',
    'dashboard.no_application': 'Not created',
    'dashboard.step_1': 'STEP 1',
    'dashboard.step_2': 'STEP 2',
    'dashboard.step_3': 'STEP 3',
    'dashboard.application_params': 'Application Parameters',
    'dashboard.file_uploads': 'File Uploads',
    'dashboard.save_changes': 'Save Changes',
    'dashboard.create_application': 'Create Application',
    'dashboard.account_settings': 'Account Settings',
    'dashboard.account_settings_subtitle': 'Manage profile data and security',
    'dashboard.profile': 'PROFILE',
    'dashboard.personal_data': 'Personal Data',
    'dashboard.security': 'SECURITY',
    'dashboard.change_password': 'Change Password',
    'dashboard.save_settings': 'Save Changes',
    'dashboard.saving': 'Saving...',
    'dashboard.name_label': 'Name',
    'dashboard.name_placeholder': 'John Doe',
    'dashboard.email_label': 'Email',
    'dashboard.email_note': 'Email cannot be changed',
    'dashboard.phone_label': 'Phone',
    'dashboard.phone_placeholder': '+998 (__) ___-__-__',
    'dashboard.current_password_label': 'Current Password',
    'dashboard.current_password_placeholder': 'Enter current password',
    'dashboard.new_password_label': 'New Password',
    'dashboard.new_password_placeholder': 'Minimum 6 characters',
    'dashboard.confirm_password_label': 'Confirm Password',
    'dashboard.confirm_password_placeholder': 'Repeat password',
    'dashboard.direction_label': 'Direction',
    'dashboard.direction_placeholder': 'Select direction',
    'dashboard.format_label': 'Participation Format',
    'dashboard.format_placeholder': 'Select format',
    'dashboard.affiliation_label': 'Affiliation (Organization / University)',
    'dashboard.affiliation_placeholder': 'Organization name',
    'dashboard.position_label': 'Position',
    'dashboard.position_placeholder': 'Select position',
    'dashboard.talk_type_label': 'Select Talk Type',
    'dashboard.talk_type_placeholder': 'Select talk type',
    'dashboard.direction_1': 'Water Diplomacy',
    'dashboard.direction_2': 'Mathematical Modeling',
    'dashboard.direction_3': 'Aral Sea Region Ecology',
    'dashboard.format_offline': 'Offline (in Tashkent)',
    'dashboard.format_online': 'Online',
    'dashboard.is_foreign_label': 'Foreign participant',
    'dashboard.is_foreign_desc': 'Check if you are a participant from a foreign country',
    'dashboard.position_professor': 'Professor',
    'dashboard.position_associate': 'Associate Professor',
    'dashboard.position_assistant': 'Assistant Professor',
    'dashboard.position_phd': 'PhD Student',
    'dashboard.position_researcher': 'Researcher',
    'dashboard.position_lecturer': 'Lecturer',
    'dashboard.position_undergrad': 'Undergraduate Student',
    'dashboard.position_other': 'Other',
    'dashboard.talk_plenary': 'Plenary',
    'dashboard.talk_section': 'Sectional',
    'dashboard.talk_panel': 'Panel',
    'dashboard.file_article': 'Scientific Paper',
    'dashboard.file_plagiarism': 'Plagiarism Report',
    'dashboard.file_payment': 'Payment Receipt',
    'dashboard.file_desc_pdf': 'PDF, DOC, DOCX (up to 10MB)',
    'dashboard.file_desc_img': 'JPG, PNG, GIF (up to 5MB)',
    'dashboard.file_uploaded': 'Uploaded',
    'dashboard.file_replace': 'Replace',
    'dashboard.file_select': 'Select file',
    'dashboard.file_uploading': 'Uploading...',
    'dashboard.instructions': 'Instructions',
    'dashboard.instr_1': 'Register for the conference',
    'dashboard.instr_2': 'Create an application by selecting direction and format',
    'dashboard.instr_3': 'Upload your scientific paper',
    'dashboard.instr_4': 'Upload the plagiarism report',
    'dashboard.instr_5': 'Pay the fee and attach the receipt',
    'dashboard.instr_6': 'Wait for confirmation',
    'dashboard.status_approved': 'Approved',
    'dashboard.status_rejected': 'Rejected',
    'dashboard.status_pending': 'Pending',
    'dashboard.loading': 'Loading...',
    'dashboard.fill_all_fields': 'Fill in all fields',
    'dashboard.save_success': 'Application saved',
    'dashboard.file_upload_success': 'File uploaded successfully',
    'dashboard.file_uploading_toast': 'Uploading file...',
    'dashboard.delete_confirm': 'Delete this file?',
    'dashboard.file_deleted': 'File deleted',
    'dashboard.fill_all_password_fields': 'Fill in all password fields',
    'dashboard.passwords_not_match': 'Passwords do not match',
    'dashboard.settings_saved': 'Settings saved',
    'dashboard.error_prefix': 'Error: ',
    'dashboard.file_upload_error_prefix': 'Upload error: ',
    'dashboard.file_delete_error_prefix': 'Delete error: ',
    // Navbar
    'navbar.cabinet': 'Dashboard',
    'navbar.logout': 'Logout',
    'navbar.lang_uz': "O'zbekcha",
    'navbar.lang_ru': 'Russian',
    'navbar.lang_en': 'English',
    // Home - Contact
    'contact.email_label': 'Email',
    'contact.phone_label': 'Phone / Telegram',
    'contact.location_label': 'Location',
    // Home - Footer
    'footer.navigation': 'Navigation',
    'footer.organizer': 'Organizer',
    'footer.developer_label': 'Developer',
    // Home - Countdown
    'countdown.days': 'days',
    'countdown.hours': 'hours',
    'countdown.mins': 'mins',
    'countdown.secs': 'secs',
    // Home - Publication accordion
    'publication.req.files_title': 'Files to Submit',
    'publication.req.file_paper': 'Paper',
    'publication.req.file_plagiarism': 'Plagiarism Report',
    'publication.req.file_info': 'Information',
    // Home - Committee members (org committee)
    'committee.org.chairman.name': 'Sodyq Safoev',
    'committee.org.chairman.role': 'First Deputy Chairman of the Senate, Rector of UWED',
    'committee.org.vice.1.name': 'Gulnoza Ismailova',
    'committee.org.vice.1.role': 'Vice-Rector for Science and Innovation, UWED',
    'committee.org.vice.2.name': 'Akram Umarov',
    'committee.org.vice.2.role': 'Deputy Director of the IAIS',
    'committee.org.vice.3.name': 'Durbek Amanov',
    'committee.org.vice.3.role': 'Director of the IAIS',
    'committee.org.vice.4.name': 'Olimjon Tuychiev',
    'committee.org.vice.4.role': 'Director of the Agency for Innovative Development',
    'committee.org.members.1.name': 'Mansur Gulyamov',
    'committee.org.members.1.role': 'IAIS Senior Fellow',
    'committee.org.members.2.name': 'Rustam Kayumov',
    'committee.org.members.2.role': 'Head of Department, UWED',
    'committee.org.members.3.name': 'Nodira Gafurova',
    'committee.org.members.3.role': 'Associate Professor, UWED',
    'committee.org.members.4.name': 'Azizbek Khonkhodjaev',
    'committee.org.members.4.role': 'Senior Lecturer, UWED',
    'committee.org.members.5.name': 'Dilnoza Sultanova',
    'committee.org.members.5.role': 'Researcher, IAIS',
    'committee.org.members.6.name': 'Jamshid Abdullaev',
    'committee.org.members.6.role': 'Expert, UWED',
    // Home - Committee members (program committee)
    'committee.prog.chairman.name': 'Sherzod Abdullaev',
    'committee.prog.chairman.role': 'Professor, Head of Department of International Relations',
    'committee.prog.vice.1.name': 'Alisher Fayzullaev',
    'committee.prog.vice.1.role': 'Professor, IAIS Senior Fellow',
    'committee.prog.vice.2.name': 'Etibor Sultanova',
    'committee.prog.vice.2.role': 'Head of Department of Social and Political Sciences',
    'committee.prog.vice.3.name': 'Ulugbek Khasanov',
    'committee.prog.vice.3.role': 'Professor, IAIS Fellow',
    'committee.prog.vice.4.name': 'Farkhod Tolipov',
    'committee.prog.vice.4.role': 'Director of Knowledge Caravan',
    'committee.prog.members.1.name': 'Bakhtiyor Ergashev',
    'committee.prog.members.1.role': "Director of Ma'no Center",
    'committee.prog.members.2.name': 'Anvar Nazirov',
    'committee.prog.members.2.role': 'Independent Expert',
    'committee.prog.members.3.name': 'Kamola Alieva',
    'committee.prog.members.3.role': 'Associate Professor, UWED',
    'committee.prog.members.4.name': 'Sardorbek Usmanov',
    'committee.prog.members.4.role': 'Senior Researcher, IAIS',
    'committee.prog.members.5.name': 'Nilufar Rakhimova',
    'committee.prog.members.5.role': 'Lecturer, UWED',
    'committee.prog.members.6.name': 'Sherzodbek Khaydarov',
    'committee.prog.members.6.role': 'Expert, IAIS',
  },
  uz: {
    'nav.home': 'Bosh sahifa',
    'nav.about': 'Konferensiya haqida',
    'nav.directions': 'Yo\'nalishlar',
    'nav.dates': 'Sanalar',
    'nav.apply': 'Ariza topshirish',
    'nav.login': 'Kirish',
    'nav.dashboard': 'Shaxsiy kabinet',
    'hero.title': 'WICAR-2026 Xalqaro ilmiy-amaliy konferensiyasi',
    'hero.subtitle': 'Barqaror rivojlanish uchun suv resurslarini boshqarishda innovatsiyalar',
    'hero.date': '2026-yil 19-may',
    'hero.location': 'Toshkent, JIDU',
    'hero.register': 'Ishtirokchilarni ro\'yxatga olish',
    'hero.countdown.title': 'Arizalar qabul qilinishi tugashiga qoldi:',
    'hero.download.info1': '1-axborot xati',
    'hero.download.info2': '2-axborot xati',
    'hero.download.collection': 'Tezislar to\'plami',
    'hero.download.program': 'Konferensiya dasturi',
    'organizer.title': 'Tashkilotchi',
    'organizer.name': 'Jahon iqtisodiyoti va diplomatiya universiteti (JIDU)',
    'organizer.desc': 'O\'zbekistonning xalqaro munosabatlar, iqtisodiyot va huquq sohasida mutaxassislar tayyorlashga ixtisoslashgan yetakchi oliy ta\'lim muassasasi.',
    'committee.title': 'Konferensiya qo\'mitalari',
    'committee.org': 'Tashkiliy qo\'mita',
    'committee.prog': 'Dasturiy qo\'mita',
    'committee.chairman': 'Rais',
    'committee.vice': 'Rais o\'rinbosarlari',
    'committee.members': 'Qo\'mita a\'zolari',
    'about.title': 'Konferensiya haqida',
    'about.goal.title': 'Konferensiya maqsadi',
    'about.goal.desc': 'Iqlim o\'zgarishi sharoitida arid zonalarda suv resurslarini samarali boshqarish muammolarini kompleks o\'rganish, innovatsion yondashuvlar va matematik/kompyuter modellashtirish usullarini ishlab chiqish, ilmiy natijalar va amaliy tajriba almashish, xalqaro hamkorlikni kengaytirish.',
    'about.format': 'Format: Gibrid (Oflayn + Onlayn)',
    'about.languages': 'Ishchi tillar: o\'zbek, rus, ingliz',
    'directions.title': 'Mavzu yo\'nalishlari',
    'directions.1.title': 'Suv diplomatiyasi va xalqaro munosabatlarda integratsiyalashgan yondashuvlar',
    'directions.1.item1': 'Suv diplomatiyasi sohasida xalqaro munosabatlar va jahon siyosatida tizimli tahlil',
    'directions.1.item2': 'Barqaror rivojlanishning iqtisodiy, ekologik va energetik jihatlari',
    'directions.1.item3': 'Barqaror rivojlanish maqsadlariga (BRM) erishishda tizimli yondashuvlar',
    'directions.2.title': 'Iqlim o\'zgarishi sharoitida suv resurslarini optimal boshqarishni matematik va kompyuter modellashtirish',
    'directions.2.item1': 'Suv resurslarini optimal boshqarish',
    'directions.2.item2': 'Suv resurslari dinamikasi va iqlim o\'zgaruvchanligini modellashtirish',
    'directions.2.item3': 'Sug\'orish tizimlarini modellashtirishda amaliy va hisoblash matematikasi usullari',
    'directions.3.title': 'Orol dengizi mintaqasidagi ekologik va gidrogeologik jarayonlar',
    'directions.3.item1': 'Orol mintaqasi gidrogeologik jarayonlarining tizimli tahlili',
    'directions.3.item2': 'Ekologik muammolarni hal qilishda sun\'iy intellekt, mashinali o\'qitish va Big Data dan foydalanish',
    'directions.3.item3': 'Ekologik va gidrogeologik jarayonlarni imitatsion va stoxastik modellashtirish',
    'dates.title': 'Muhim sanalar',
    'dates.item1.title': 'Arizalar va tezislar qabuli',
    'dates.item1.date': '2026-yil 10-maygacha',
    'dates.item2.title': 'Ishtirokni tasdiqlash',
    'dates.item2.date': '2026-yil 12-maygacha',
    'dates.item3.title': 'Konferensiya dasturi',
    'dates.item3.date': '2026-yil 12-may',
    'dates.item4.title': 'Konferensiya kuni',
    'dates.item4.date': '2026-yil 19-may',
    'fees.title': 'Tashkiliy badal',
    'fees.local': 'O\'zbekistonlik ishtirokchilar: 200 000 UZS',
    'fees.foreign.offline': 'Xorijiy ishtirokchilar (oflayn): 20 USD',
    'fees.foreign.online': 'Xorijiy ishtirokchilar (onlayn): Bepul',
    'fees.note': '* To\'lov faqat tashkiliy qo\'mita tomonidan ariza ma\'qullanganidan keyin amalga oshiriladi.',
    'publication.title': 'Nashr va talablar',
    'publication.general': 'Materiallar UDC, BBK, ISBN va DOI berilgan holda to\'plamda nashr etiladi. Har bir ishtirokchi sertifikat oladi.',
    'publication.req.title': 'Rasmiylashtirish talablari',
    'publication.req.volume': 'Hajmi: 6–8 bet (A4)',
    'publication.req.format': 'Format: DOC/DOCX, Times New Roman 12pt shrifti',
    'publication.req.spacing': 'Qatorlar oralig\'i: 1.5, xatboshi: 1.25 sm, hoshiyalar: 20 mm',
    'publication.req.originality': 'Originallik: kamida 70% (muallif tomonidan tekshiriladi)',
    'publication.req.files': 'Topshirish uchun ttmm.conf@uwed.uz manziliga UCHTA fayl yuboring: Maqola, Antiplagiat, Ma\'lumot.',
    'contact.title': 'Kontaktlar',
    'contact.address': '100007, Toshkent sh., Mustaqillik shoh ko\'chasi, 54',
    'contact.phone': '+998 90 985-80-44',
    'contact.email': 'ttmm.conf@uwed.uz',
    'contact.form.title': 'Biz bilan bog\'lanish',
    'contact.name': 'Ismingiz',
    'contact.message': 'Xabaringiz',
    'contact.send': 'Xabarni yuborish',
    'contact.success': 'Xabar muvaffaqiyatli yuborildi!',
    'footer.rights': 'Barcha huquqlar himoyalangan',
    // Auth
    'auth.login': 'Kirish',
    'auth.register': "Ro'yxatdan o'tish",
    'auth.login_success': 'Xush kelibsiz!',
    'auth.login_error': "Kirish xatosi",
    'auth.register_success': "Ro'yxatdan o'tish muvaffaqiyatli! Endi kirishingiz mumkin.",
    'auth.register_error': "Ro'yxatdan o'tish xatosi",
    'auth.forgot': 'Unutdingizmi?',
    'auth.email_label': 'Email manzili',
    'auth.password_label': 'Parol',
    'auth.email_placeholder': 'name@university.edu',
    'auth.full_name_label': "To'liq ism",
    'auth.phone_label': 'Telefon raqami',
    'auth.full_name_placeholder': 'Ivanov Ivan Ivanovich',
    'auth.phone_placeholder': '+998 (__) ___-__-__',
    'auth.not_registered': 'Konferensiyada birinchi marta?',
    'auth.already_registered': "Allaqachon ro'yxatdan o'tganmisiz?",
    'auth.register_link': "Ro'yxatdan o'tish",
    'auth.login_link': 'Kirish',
    'auth.creating_account': "Hisob yaratilmoqda...",
    'auth.processing': "Qayta ishlanmoqda...",
    // Login page
    'login.title': 'Ilmiy hamjamiyatga kirish',
    'login.subtitle': "Nashrlaringizni boshqarish va konferensiya sessiyalarida ishtirok etish uchun shaxsiy kabinetingizga kiring.",
    'login.secure_access': 'Secure Access',
    'login.location': 'Toshkent, O\'zbekiston',
    // Register page
    'register.title': 'Ilmiy muloqotga qo\'shiling',
    'register.publications': 'Nashrlar',
    'register.publications_desc': 'RINTC/Scopus to\'plamida nashr qilish imkoniyati',
    'register.networking': 'Netvorking',
    'register.networking_desc': 'Soha yetakchi mutaxassislari bilan tajriba almashish',
    'register.certification': 'Sertifikatsiya',
    'register.certification_desc': "Konferensiya ishtirokchisining rasmiy sertifikati",
    'register.deadline': "Ro'yxatdan o'tish tugaydi: 2026-yil 15-may",
    // Dashboard
    'dashboard.title': "Shaxsiy kabinet",
    'dashboard.subtitle': "WICAR-2026 konferensiyasida ishtirokingizni boshqaring",
    'dashboard.overview': "Ko'rib chiqish",
    'dashboard.settings': 'Sozlamalar',
    'dashboard.participant': 'Ishtirokchi',
    'dashboard.application_status': "Ariza holati",
    'dashboard.no_application': "Yaratilmagan",
    'dashboard.step_1': "1-QADAM",
    'dashboard.step_2': "2-QADAM",
    'dashboard.step_3': "3-QADAM",
    'dashboard.application_params': "Ishtirok parametrlari",
    'dashboard.file_uploads': "Hujjatlarni yuklash",
    'dashboard.save_changes': "O'zgarishlarni saqlash",
    'dashboard.create_application': "Ariza yaratish",
    'dashboard.account_settings': "Hisob sozlamalari",
    'dashboard.account_settings_subtitle': "Profil ma'lumotlari va xavfsizlikni boshqarish",
    'dashboard.profile': "PROFIL",
    'dashboard.personal_data': "Shaxsiy ma'lumotlar",
    'dashboard.security': "XAVFSIZLIK",
    'dashboard.change_password': "Parolni o'zgartirish",
    'dashboard.save_settings': "O'zgarishlarni saqlash",
    'dashboard.saving': "Saqlanmoqda...",
    'dashboard.name_label': "Ism",
    'dashboard.name_placeholder': 'Ivanov Ivan Ivanovich',
    'dashboard.email_label': "Email",
    'dashboard.email_note': "Emailni o'zgartirib bo'lmaydi",
    'dashboard.phone_label': "Telefon",
    'dashboard.phone_placeholder': '+998 (__) ___-__-__',
    'dashboard.current_password_label': "Joriy parol",
    'dashboard.current_password_placeholder': "Joriy parolni kiriting",
    'dashboard.new_password_label': "Yangi parol",
    'dashboard.new_password_placeholder': "Kamida 6 ta belgi",
    'dashboard.confirm_password_label': "Parolni tasdiqlang",
    'dashboard.confirm_password_placeholder': "Parolni qaytaring",
    'dashboard.direction_label': "Yo'nalish",
    'dashboard.direction_placeholder': "Yo'nalishni tanlang",
    'dashboard.format_label': "Ishtirok formati",
    'dashboard.format_placeholder': "Formatni tanlang",
    'dashboard.affiliation_label': "Affiliation (Tashkilot / OTM)",
    'dashboard.affiliation_placeholder': "Tashkilot nomi",
    'dashboard.position_label': "Lavozim",
    'dashboard.position_placeholder': "Lavozimni tanlang",
    'dashboard.talk_type_label': "Ma'ruza turini tanlang",
    'dashboard.talk_type_placeholder': "Ma'ruza turini tanlang",
    'dashboard.direction_1': "Suv diplomatiyasi",
    'dashboard.direction_2': "Matematik modellashtirish",
    'dashboard.direction_3': "Orol dengizi mintaqasi ekologiyasi",
    'dashboard.format_offline': "Of layn (Toshkentda)",
    'dashboard.format_online': "Onlayn",
    'dashboard.is_foreign_label': "Xorijiy ishtirokchi",
    'dashboard.is_foreign_desc': "Agar siz xorijiy mamlakatdan ishtirokchi bo'lsangiz, belgilang",
    'dashboard.position_professor': "Professor",
    'dashboard.position_associate': "Dotsent",
    'dashboard.position_assistant': "Assistant Professor",
    'dashboard.position_phd': "PhD talabasi",
    'dashboard.position_researcher': "Tadqiqotchi",
    'dashboard.position_lecturer': "Ma'ruzachi",
    'dashboard.position_undergrad': "Bakalavr talabasi",
    'dashboard.position_other': "Boshqa",
    'dashboard.talk_plenary': "Plenar",
    'dashboard.talk_section': "Sessiyaviy",
    'dashboard.talk_panel': "Panel",
    'dashboard.file_article': "Ilmiy maqola",
    'dashboard.file_plagiarism': "Antiplagiat",
    'dashboard.file_payment': "To'lov cheki",
    'dashboard.file_desc_pdf': "PDF, DOC, DOCX (10MB gacha)",
    'dashboard.file_desc_img': "JPG, PNG, GIF (5MB gacha)",
    'dashboard.file_uploaded': "Yuklandi",
    'dashboard.file_replace': "Almashtirish",
    'dashboard.file_select': "Faylni tanlang",
    'dashboard.file_uploading': "Yuklanmoqda...",
    'dashboard.instructions': "Yo'riqnomalar",
    'dashboard.instr_1': "Konferensiyada ro'yxatdan o'ting",
    'dashboard.instr_2': "Yo'nalish va formatni tanlab ariza yarating",
    'dashboard.instr_3': "Ilmiy maqolangizni yuklang",
    'dashboard.instr_4': "Antiplagiat hisobotini yuklang",
    'dashboard.instr_5': "Badalni to'lang va chekini biriktiring",
    'dashboard.instr_6': "Tasdiqni kuting",
    'dashboard.status_approved': "Tasdiqlandi",
    'dashboard.status_rejected': "Rad etildi",
    'dashboard.status_pending': "Ko'rib chiqilmoqda",
    'dashboard.loading': "Yuklanmoqda...",
    'dashboard.fill_all_fields': "Barcha maydonlarni to'ldiring",
    'dashboard.save_success': "Ariza saqlandi",
    'dashboard.file_upload_success': "Fayl muvaffaqiyatli yuklandi",
    'dashboard.file_uploading_toast': "Fayl yuklanmoqda...",
    'dashboard.delete_confirm': "Ushbu faylni o'chirasizmi?",
    'dashboard.file_deleted': "Fayl o'chirildi",
    'dashboard.fill_all_password_fields': "Barcha parol maydonlarini to'ldiring",
    'dashboard.passwords_not_match': "Parollar mos kelmaydi",
    'dashboard.settings_saved': "Sozlamalar saqlandi",
    'dashboard.error_prefix': "Xato: ",
    'dashboard.file_upload_error_prefix': "Yuklash xatosi: ",
    'dashboard.file_delete_error_prefix': "O'chirish xatosi: ",
    // Navbar
    'navbar.cabinet': "Kabinet",
    'navbar.logout': "Chiqish",
    'navbar.lang_uz': "O'zbekcha",
    'navbar.lang_ru': "Ruscha",
    'navbar.lang_en': "Inglizcha",
    // Home - Contact
    'contact.email_label': "Email",
    'contact.phone_label': "Telefon / Telegram",
    'contact.location_label': "Manzil",
    // Home - Footer
    'footer.navigation': "Navigatsiya",
    'footer.organizer': "Tashkilotchi",
    'footer.developer_label': "Yaratuvchi",
    // Home - Countdown
    'countdown.days': "kun",
    'countdown.hours': "soat",
    'countdown.mins': "daq",
    'countdown.secs': "son",
    // Home - Publication accordion
    'publication.req.files_title': "Yuklanadigan fayllar",
    'publication.req.file_paper': "Maqola",
    'publication.req.file_plagiarism': "Antiplagiat",
    'publication.req.file_info': "Ma'lumot",
    // Home - Committee members (org committee)
    'committee.org.chairman.name': "Sodyq Safoev",
    'committee.org.chairman.role': "Senatning birinchi o'rinbosari, JIDU rektori",
    'committee.org.vice.1.name': "Gulnoza Ismailova",
    'committee.org.vice.1.role': "Ilm-fan va innovatsiyalar bo'yicha prorektor, JIDU",
    'committee.org.vice.2.name': "Akram Umarov",
    'committee.org.vice.2.role': "XKAIC direktori o'rinbosari",
    'committee.org.vice.3.name': "Durbek Amanov",
    'committee.org.vice.3.role': "XKAIC direktori",
    'committee.org.vice.4.name': "Olimjon Tuychiev",
    'committee.org.vice.4.role': "Innovatsion rivojlanish agentligi direktori",
    'committee.org.members.1.name': "Mansur Gulyamov",
    'committee.org.members.1.role': "XKAIC katta ilmiy xodim",
    'committee.org.members.2.name': "Rustam Kayumov",
    'committee.org.members.2.role': "JIDU kafedra mudiri",
    'committee.org.members.3.name': "Nodira Gafurova",
    'committee.org.members.3.role': "JIDU dotsenti",
    'committee.org.members.4.name': "Azizbek Khonkhodjaev",
    'committee.org.members.4.role': "Katta o'qituvchi, JIDU",
    'committee.org.members.5.name': "Dilnoza Sultanova",
    'committee.org.members.5.role': "XKAIC ilmiy xodimi",
    'committee.org.members.6.name': "Jamshid Abdullaev",
    'committee.org.members.6.role': "JIDU eksperti",
    // Home - Committee members (program committee)
    'committee.prog.chairman.name': "Sherzod Abdullaev",
    'committee.prog.chairman.role': "Professor, Xalqaro munosabatlar kafedrasi mudiri",
    'committee.prog.vice.1.name': "Alisher Fayzullaev",
    'committee.prog.vice.1.role': "Professor, XKAIC katta ilmiy xodim",
    'committee.prog.vice.2.name': "Etibor Sultanova",
    'committee.prog.vice.2.role': "Ijtimoiy-siyosiy fanlar kafedrasi mudiri",
    'committee.prog.vice.3.name': "Ulugbek Khasanov",
    'committee.prog.vice.3.role': "Professor, XKAIC ilmiy xodimi",
    'committee.prog.vice.4.name': "Farkhod Tolipov",
    'committee.prog.vice.4.role': "Knowledge Caravan direktori",
    'committee.prog.members.1.name': "Bakhtiyor Ergashev",
    'committee.prog.members.1.role': "Ma'no Center direktori",
    'committee.prog.members.2.name': "Anvar Nazirov",
    'committee.prog.members.2.role': "Mustaqil ekspert",
    'committee.prog.members.3.name': "Kamola Alieva",
    'committee.prog.members.3.role': "JIDU dotsenti",
    'committee.prog.members.4.name': "Sardorbek Usmanov",
    'committee.prog.members.4.role': "XKAIC katta ilmiy xodimi",
    'committee.prog.members.5.name': "Nilufar Rakhimova",
    'committee.prog.members.5.role': "JIDU o'qituvchisi",
    'committee.prog.members.6.name': "Sherzodbek Khaydarov",
    'committee.prog.members.6.role': "XKAIC eksperti",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['ru']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
