# Generated by Django 5.0.4 on 2026-04-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True, verbose_name='Chat ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Администратор Telegram',
                'verbose_name_plural': 'Администраторы Telegram',
                'db_table': 'telegram_admins',
            },
        ),
    ]
