# Generated by Django 5.0.4 on 2026-04-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramadmin',
            name='role',
            field=models.CharField(choices=[('all', 'Все уведомления'), ('payment', 'Только оплаты'), ('article', 'Только статьи')], default='all', max_length=20, verbose_name='Роль'),
        ),
    ]
