# Generated by Django 5.0.4 on 2026-04-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('organizing', 'Организационный комитет'), ('program', 'Программный комитет')], max_length=20, unique=True, verbose_name='Тип комитета')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Комитет',
                'verbose_name_plural': 'Комитеты',
                'db_table': 'committees',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('chairman', 'Председатель'), ('vice', 'Заместитель председателя'), ('member', 'Член комитета')], max_length=20, verbose_name='Роль')),
                ('position', models.CharField(max_length=255, verbose_name='Должность/Организация')),
                ('photo', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committees.committee', verbose_name='Комитет')),
            ],
            options={
                'verbose_name': 'Член комитета',
                'verbose_name_plural': 'Члены комитетов',
                'db_table': 'committee_members',
                'ordering': ['committee', 'order'],
            },
        ),
    ]
