# Generated by Django 5.0.4 on 2026-04-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='committees/photos/', verbose_name='Фото'),
        ),
    ]
